spring:
  profiles:
    active: dev
  codec:
    max-in-memory-size: 10MB

server:
  port: 9090
chunk:
  size: 10000
chefs:
  url: https://submit.digital.gov.bc.ca/app/api/v1/
  wait: 100
  forms:
    oldStatusTracker:
      formId: 
      apiKey: 
    statusTracker:
      formId: 
      apiKey: 
      
    